### ISSUE TITLE
Cinnamon 2.2 compability

### ISSUE THREAD

**Issue by Manuel-Kehl** [Koutch/Cinnamon-systray-collapsible#1]
There appears to be a bug when used with Cinnamon 2.2.
Neither collapse/expand  buttons are displayed, nor can the context menu be opened.

**Comment by Koutch** [comment]
I've just install mint 17 (and cinnamon 2.2) and I've also this bug . I'm working on it ;)

**Comment by Manuel-Kehl** [comment]
Thanks :-) I'm looking forward to use that great Plugin again!

**Comment by Koutch** [comment]
it works for me now ;) 
new version is published on  http://cinnamon-spices.linuxmint.com/applets

**Comment by Manuel-Kehl** [comment]
Thanks a lot! It works as expected :+1: 
The Issue can be closed :-)
