### ISSUE TITLE
Doesn't work on Cinnamon 2.2.16

### ISSUE THREAD

**Issue by kowalcj0** [Koutch/Cinnamon-systray-collapsible#3]
Hi,

I'd love to use this plugin but unfortunately it doesn't work on Linux Mint 17 x64 with Cinnamon 2.2.16
Here's a screencast showing the behaviour:
https://drive.google.com/file/d/0B4dOfgrzdI7MeWNhUjRxMDlmZUE/view?usp=sharing

I'd be great if you could fix the problem,

Cheers,
Janusz

**Comment by ghost** [comment]
Working partially here, same system specs. Some icons get hidden (IM applications + update manager) but I can add further ones: they "slip" outside the fold-able area and the icons inside become grey squares. Finishing the "Panel Edit mode" return the broken icons to normal. The rest works as expected.

Thanks a lot for the spice btw, koutch!

**Comment by Koutch** [comment]
Hi 
@kowalcj0 : on your screencat, I see the update manager icon before you add my applet to the panel. you have to remove from the panel the original "system tray" applet. then to hide an icon you have to right-click close to an icon (e.g. update-manager) to open the context menu like in the [screenshot](http://cinnamon-spices.linuxmint.com/uploads/applets/C4G6-ONU3-PZ76.png)

@kehugter : my applet is juste to hide system tray icons. You can't drag other applet in it to hide them ;).

**Comment by ghost** [comment]
Thanks for the clarification.

**Comment by Koutch** [comment]
you're welcome ;)
you may know it but there is [show/hide applets 1.2.4](http://cinnamon-spices.linuxmint.com/applets/view/169) to do this
